### ISSUE TITLE
tomcat-jta codeCoverage is missing ${jvm.args.jacoco}

### ISSUE THREAD

**Issue by zhfeng** [web-servers/narayana-tomcat#18]
It looks like we missed this property in [decouple from the narayana parent](https://github.com/web-servers/narayana-tomcat/pull/6). So I need to add it back and also the jacoco-maven-plugin.
This causes the [Narayana CI codeCoverage job](http://narayanaci1.eng.hst.ams2.redhat.com/job/narayana-codeCoverage/44/) failing.

/cc @tomjenkinson @Karm 

Do we still need this code coverage testing in the narayana-tomcat or just remove it at all ?

**Comment by Karm** [comment]
@zhfeng We need the test coverage testing. It would be very helpful to have it back. Let us know whether you have it ready somewhere and could push it here or whether one of us should do the deed. 
Thank you :+1:  :gear:

**Comment by jfclere** [comment]
@zhfeng where does it need to go? In Arquillian so I guess in BaseITCase.java but where?

**Comment by Karm** [comment]
I think I almost have it, using Arq jacoco extension...verifying the results make sense now.  it works for the unit tests already.

**Comment by Karm** [comment]
Resolved in #21
