### ISSUE TITLE
Upgrade the arquillian-container-tomcat to 1.1.0.Final to support with JDK9+

### ISSUE THREAD

**Issue by zhfeng** [web-servers/narayana-tomcat#20]
It has the new release https://github.com/arquillian/arquillian-container-tomcat/pull/41#issuecomment-415353562

**Comment by zhfeng** [comment]
@Karm I think you need to check the CI script since you build the SNAPSHOT before ?

**Comment by jfclere** [comment]
JDK9+ so JDK11

**Comment by Karm** [comment]
Fixed
